DROP TABLE IF EXISTS GeoCodes;

CREATE TABLE GeoCodes (
  Id INT AUTO_INCREMENT  PRIMARY KEY,
  BreweryId INT NOT NULL,
  Latitude DOUBLE NOT NULL,
  Longitude DOUBLE NOT NULL
);

DROP TABLE IF EXISTS Beers;

CREATE TABLE Beers (
  Id INT AUTO_INCREMENT  PRIMARY KEY,
  BreweryId INT NOT NULL,
  BeerName VARCHAR(150)
);