DROP TABLE IF EXISTS GeoCodes;

CREATE TABLE GeoCodes (
  Id INT AUTO_INCREMENT  PRIMARY KEY,
  BreweryId INT NOT NULL,
  Latitude DOUBLE NOT NULL,
  Longitude DOUBLE NOT NULL
);

DROP TABLE IF EXISTS Beers;

CREATE TABLE Beers (
  Id INT AUTO_INCREMENT  PRIMARY KEY,
  BreweryId INT NOT NULL,
  BeerName VARCHAR(150)
);

DROP TABLE IF EXISTS Breweries;

CREATE TABLE Breweries (
  Id INT AUTO_INCREMENT  PRIMARY KEY,
  Name VARCHAR(150),
  Address VARCHAR(150),
  City VARCHAR(50),
  State VARCHAR(50),
  Code VARCHAR(20),
  Country VARCHAR(50)
);